openapi: 3.0.3
info:
  title: Backend for JS project
  version: 1.0.0
  contact: {}
servers:
  - url: http://localhost
  - url: localhost
paths:
  /api/refresh:
    post:
      tags:
        - Auth
      summary: Refresh
      description: Refresh
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: '{{refreshToken}}'
            examples:
              Refresh:
                value:
                  refreshToken: '{{refreshToken}}'
      responses:
        '200':
          description: ''
  /api/login:
    post:
      tags:
        - Auth
      summary: Log In
      description: Log In
      operationId: logIn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@itlogia.ru
                password:
                  type: string
                  example: 12345678Qq
                rememberMe:
                  type: boolean
                  example: true
            examples:
              Log In:
                value:
                  email: test@itlogia.ru
                  password: 12345678Qq
                  rememberMe: true
      responses:
        '200':
          description: ''
  /api/signup:
    post:
      tags:
        - Auth
      summary: Sign Up
      description: Sign Up
      operationId: signUp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: roman@itlogia.ru
                name:
                  type: string
                  example: Роман
                password:
                  type: string
                  example: 12345678Qq
                passwordRepeat:
                  type: string
                  example: 12345678Qq
            examples:
              Sign Up:
                value:
                  email: roman@itlogia.ru
                  name: Роман
                  password: 12345678Qq
                  passwordRepeat: 12345678Qq
      responses:
        '200':
          description: ''
  /api/logout:
    post:
      tags:
        - Auth
      summary: Log Out
      description: Log Out
      operationId: logOut
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjI5OTczNDIsImV4cCI6MTY2NTU4OTM0Mn0.suPnUi_M_2wpWRtJ9GfVgR0hQ5jYqIi3ShGK_iyPqD4
            examples:
              Log Out:
                value:
                  refreshToken: >-
                    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjI5OTczNDIsImV4cCI6MTY2NTU4OTM0Mn0.suPnUi_M_2wpWRtJ9GfVgR0hQ5jYqIi3ShGK_iyPqD4
      responses:
        '200':
          description: ''
  /api/categories/expense:
    get:
      tags:
        - Category-expense
      summary: Get categories
      description: Get categories
      operationId: getCategories
      responses:
        '200':
          description: ''
    post:
      tags:
        - Category-expense
      summary: Create category
      description: Create category
      operationId: createCategory
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJyb21hbkBpdGxvZ2lhLnJ1IiwiaWF0IjoxNjYzMDE4NjA0LCJleHAiOjE2NjMwMTk1MDR9.vzEXz7z4ybMmL3WOTUqY-U7Sb65_qR3bbPXrJFixIeo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Новая категория маяк
            examples:
              Create category:
                value:
                  title: Новая категория маяк
      responses:
        '200':
          description: ''
  /api/categories/expense/1:
    get:
      tags:
        - Category-expense
      summary: Get category
      description: Get category
      operationId: getCategory
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTczMjYsImV4cCI6MTY2MzA5ODIyNn0.iKu1srt3uoLIZsdcVyGc20D6qlPKLfLmYxRu-KLL0xQ
      responses:
        '200':
          description: ''
  /api/categories/expense/{id}:
    put:
      tags:
        - Category-expense
      summary: Update category
      description: Update category
      operationId: updateCategory
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJyb21hbkBpdGxvZ2lhLnJ1IiwiaWF0IjoxNjYzMDE4NjA0LCJleHAiOjE2NjMwMTk1MDR9.vzEXz7z4ybMmL3WOTUqY-U7Sb65_qR3bbPXrJFixIeo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Измененная
            examples:
              Update category:
                value:
                  title: Измененная
      responses:
        '200':
          description: ''
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: '2'
  /api/categories/expense/3:
    delete:
      tags:
        - Category-expense
      summary: Delete category
      description: Delete category
      operationId: deleteCategory
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJyb21hbkBpdGxvZ2lhLnJ1IiwiaWF0IjoxNjYzMDE4NjA0LCJleHAiOjE2NjMwMTk1MDR9.vzEXz7z4ybMmL3WOTUqY-U7Sb65_qR3bbPXrJFixIeo
      responses:
        '200':
          description: ''
  /api/operations:
    get:
      tags:
        - Operations
      summary: Get operations
      description: Get operations
      operationId: getOperations
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTc2MjIsImV4cCI6MTY2MzA5ODUyMn0.YHLAiEh_u-dH9qKxTq0Mw_Vfzdp4zweM5H5bqKrcc08
        - name: period
          in: query
          schema:
            type: string
            example: all
        - name: dateFrom
          in: query
          schema:
            type: string
            example: '2022-01-01'
        - name: dateTo
          in: query
          schema:
            type: string
            example: '2022-09-13'
        - name: type
          in: query
          schema:
            type: string
            example: income
      responses:
        '200':
          description: ''
    post:
      tags:
        - Operations
      summary: Create operation
      description: Create operation
      operationId: createOperation
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTg2MzUsImV4cCI6MTY2MzA5OTUzNX0.94YDRhYXPMy8nCdFaRouRY2fzDeY2hJJdPsSCb5j4JA
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 250
                category_id:
                  type: number
                  example: 2
                comment:
                  type: string
                  example: Мусорам на лапу
                date:
                  type: string
                  example: '2023-03-04'
                type:
                  type: string
                  example: expense
            examples:
              Create operation:
                value:
                  amount: 250
                  category_id: 2
                  comment: Мусорам на лапу
                  date: '2023-03-04'
                  type: expense
      responses:
        '200':
          description: ''
  /api/operations/{id}:
    get:
      tags:
        - Operations
      summary: Get operation
      description: Get operation
      operationId: getOperation
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwMTk3ODYsImV4cCI6MTY2MzAyMDY4Nn0.fqfnXG42iIT5YBb-hihozpLJ2Cg2mTD1PHXBvjt3lVw
      responses:
        '200':
          description: ''
    delete:
      tags:
        - Operations
      summary: Delete operation
      description: Delete operation
      operationId: deleteOperation
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwMjA3MTcsImV4cCI6MTY2MzAyMTYxN30.CeqNhbJ0ZcQ9imcLQ7-F9q705BSLZlUbMeeOZwtJUh8
      responses:
        '200':
          description: ''
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: '6'
  /api/operations/2:
    put:
      tags:
        - Operations
      summary: Update operation
      description: Update operation
      operationId: updateOperation
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTc2MjIsImV4cCI6MTY2MzA5ODUyMn0.YHLAiEh_u-dH9qKxTq0Mw_Vfzdp4zweM5H5bqKrcc08
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 150
                category_id:
                  type: number
                  example: 3
                comment:
                  type: string
                  example: wtf
                date:
                  type: string
                  example: '2022-02-02'
                type:
                  type: string
                  example: expense
            examples:
              Update operation:
                value:
                  amount: 150
                  category_id: 3
                  comment: wtf
                  date: '2022-02-02'
                  type: expense
      responses:
        '200':
          description: ''
  /api/categories/income:
    get:
      tags:
        - Category-income
      summary: Get categories
      description: Get categories
      operationId: getCategories1
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwMTc5NDgsImV4cCI6MTY2MzAxODg0OH0.-jKCuStW7w9y6ZPRQZ35jeBYEIBi3izJhuHAqZXAR7k
      responses:
        '200':
          description: ''
    post:
      tags:
        - Category-income
      summary: Create category
      description: Create category
      operationId: createCategory1
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTczMjYsImV4cCI6MTY2MzA5ODIyNn0.iKu1srt3uoLIZsdcVyGc20D6qlPKLfLmYxRu-KLL0xQ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Новая категория
            examples:
              Create category:
                value:
                  title: Новая категория
      responses:
        '200':
          description: ''
  /api/categories/income/1:
    get:
      tags:
        - Category-income
      summary: Get category
      description: Get category
      operationId: getCategory1
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwMTc5NDgsImV4cCI6MTY2MzAxODg0OH0.-jKCuStW7w9y6ZPRQZ35jeBYEIBi3izJhuHAqZXAR7k
      responses:
        '200':
          description: ''
    put:
      tags:
        - Category-income
      summary: Update category
      description: Update category
      operationId: updateCategory1
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTczMjYsImV4cCI6MTY2MzA5ODIyNn0.iKu1srt3uoLIZsdcVyGc20D6qlPKLfLmYxRu-KLL0xQ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Измененная
            examples:
              Update category:
                value:
                  title: Измененная
      responses:
        '200':
          description: ''
  /api/categories/income/2:
    delete:
      tags:
        - Category-income
      summary: Delete category
      description: Delete category
      operationId: deleteCategory1
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwMTc5NDgsImV4cCI6MTY2MzAxODg0OH0.-jKCuStW7w9y6ZPRQZ35jeBYEIBi3izJhuHAqZXAR7k
      responses:
        '200':
          description: ''
  /api/balance:
    get:
      tags:
        - Balance
      summary: Get Balance
      description: Get Balance
      operationId: getBalance
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTczMjYsImV4cCI6MTY2MzA5ODIyNn0.iKu1srt3uoLIZsdcVyGc20D6qlPKLfLmYxRu-KLL0xQ
      responses:
        '200':
          description: ''
    put:
      tags:
        - Balance
      summary: Update Balance
      description: Update Balance
      operationId: updateBalance
      parameters:
        - name: x-auth-token
          in: header
          schema:
            type: string
            example: >-
              eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGl0bG9naWEucnUiLCJpYXQiOjE2NjMwOTczMjYsImV4cCI6MTY2MzA5ODIyNn0.iKu1srt3uoLIZsdcVyGc20D6qlPKLfLmYxRu-KLL0xQ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newBalance:
                  type: number
                  example: 1000
            examples:
              Update Balance:
                value:
                  newBalance: 1000
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags:
  - name: Auth
  - name: Category-expense
  - name: Operations
  - name: Category-income
  - name: Balance

